services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"

  livebook:
    image: ghcr.io/livebook-dev/livebook:latest
    environment:
      LIVEBOOK_TOKEN_ENABLED: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./:/data
    depends_on:
      - db